apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.file.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Release.Name }}-aws-secretsmanager
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.file.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.file.awsSecretName }}
