apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecrets.awsRegion }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.externalSecrets.credentialsSecretName }}
            key: access-key
          secretAccessKeySecretRef:
            name: {{ .Values.externalSecrets.credentialsSecretName }}
            key: secret-access-key
          sessionTokenSecretRef:
            name: {{ .Values.externalSecrets.credentialsSecretName }}
            key: session-token
