apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app1-external-secret-env
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: app1-aws-secretsmanager
    kind: SecretStore
  target:
    name: app1-secret-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: argocd-demo/app-secrets
