apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: app1-aws-secretsmanager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-secretsmanager-credentials
            key: access-key
          secretAccessKeySecretRef:
            name: aws-secretsmanager-credentials
            key: secret-access-key
          sessionTokenSecretRef:
            name: aws-secretsmanager-credentials
            key: session-token
